research_task:
  description: |
    Research the following topic and provide key findings:
    {topic}
    
    Your research should include:
    1. Main points and key facts
    2. Supporting evidence
    3. Any relevant statistics or data
    
    Format your findings in a clear, structured manner.
  expected_output: |
    A comprehensive research report containing key findings, supporting evidence,
    and relevant statistics about the topic, formatted in a clear and structured manner.
  agent: research_agent

writing_task:
  description: |
    Using the research provided, create a comprehensive article about:
    {topic}
    
    The article should:
    1. Have a clear introduction
    2. Include all key points from the research
    3. Be well-structured and engaging
    4. End with a strong conclusion
    
    Research findings:
  expected_output: |
    A well-written, engaging article that effectively communicates the research findings
    with a clear structure, including introduction, key points, and conclusion.
  agent: writer_agent
  context: [research_task] 